language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: GL2EgBwxM2EM8Sz7MvsognGLTTpuotImlBWQQmekc8nYGxNl4uXzNmFlvi5drZXei0sRjzE+RtW+MzdaMVExutNv59y0fEje8uaIh1IFoP0Hh7ZD3dv3w3h4r6+WT4H0Ux9/HLEOQt87KKbhQC5A7zv/n1Qu+jTlk0y2yf6U5vD9Zpn1+6wcOa81zNpw1Vwl/XPaiI2MjYBE5jqO6x6EhF+kNXVk1gy9hfDslj+a8DlQn2yHLi7DXrYGmecPd1wDN+ejxCidQD5tedVutmTsze8j3h/uGNcXFR/+ZXQ9eQxuUvgcDFacv0KDf6L1dgjy+G1eNxyzwtn7nEKsxt32tA/i/ESzj1D2swWMjUj6uvD6NJXXrv0IAmQ5UkzAsIeOChAt1cfR8De3vvS24eGqX/rmFigKabwKDONGlwOzKnQ4edFmsLZYAgFAeJueMAWO4Zufcvh5CWRRw0TKQ0k1HQ7fLpu/lti1G5axLCc7DBeasXUSwcVyBzljTDJpJ6t7cG8FxChCXQpC5rxPDU+4ttkBiyqjS6kZWGRHFg/Yfb1AMtJGUgQie4JSeJV7STlVCAY5CWS5tOK+13nrXqWHXNpQuVZdb8ofN1mGDX/Q4xz66VPQO+ECHreaFODYqL9QyPDJmdNrF9TYKP3XomG4tUa5vJwD+AzM1Tl6TfvJUZw=
  - secure: sil5H9+j9g3xkCZcg9mnqgUPZz8uQLHSuCfKq96h+68LXiszOQ6r4KntATBAlVhwWRgS0ndu21EJ+DhVJ0O6M/ckLxP8vdErFbtlOJ/c2R/RtLxtKRujBJ5kGi+tLy3UcSYq9XAou2IzEwylz0pYhTnPeWrdxWrcwULkofYvZYB3gQpE5qCI3NMBOTe1q+5uX6C5MusEcq6u4o3urmwyeBFIsaGHSk0bAzGAFRpL8Fg7W/F4JLVIS0wev5S//snN1BSo9q6ySFW53iNqZnUNR1TkFvP2GZIRw2vuC4mdfQfqAGJ73FXLat6nce0XR63KySIsnApEb35amb+X3VDi4FqZPucV70KCx76eoAe9ZH8LX/1tu9efbidKBwsL3L/lg33VnNho7BONM2UEUynrjve1jXruPSvMz1UEWylGLEatpXloiOCodmGnSEOA0rYlcJRWkETZY6MDQHN1Km14wECxZTaQCNaecTxAO2RdWRcScbg3TfjTc4zIK5V7NV6qXtTOwqd8koDF8YFF41tV2tT14Zcr1RufsGATGPO7YP7fPE4L3LIM+//ETG6lqpztLzdXhiyUo4O//hHTOQXDlu1nnLf1pTxN4aoJLBoEz2yNRyoDAepOUJhROKQLBs7ZBzu59OmYML8uPxsVz0jggHZfQHZgvvT0GJjJpZT4Vi0=
