language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: VdTun9lq/A0WJXFMGkRFgtm6hhgDx0aGhj7Dm7Jzp6hKhZ/ioX6YmZNvfgwf/yKhsjBcxo4Y6kKoiu+lnp3B5sb0Ba77IGu4J0MTP8lYpF52HqkNH6D32/UPp6w+YwR0ND2deMdj4DMw0b0ST6PpfRqxfzpoKSkNSuBQsohf8VZN8GKtKAbBgJfUbqIq2kEw8xdm2TGq3ZQ0Xwrb51w59xYd+ymJk/MB7CTT0HdpbgIMN7BMhD+QmtgrLu1KsATcS7TdGqlc83Ctrq0Traye1nWhPZPQt8pj9xnHEONlEL/4ksxheUT71c21ePJgRrBhYK1BgIZMMj49bfjzyq1blOn49NN3QVWUetWTJnfi8urFIQwHDT0Y0EhZb2zr1nH2O9kb7nKV5pZM73/8oFvZZbigZZNZAKJU8NqgR843LO56aTQkcSJb8MKo0iH/WgOTH9urjst4EKJc4jWBva0pzc29o0k7qp08cWVntTGBpiLXZaMf+/zzZm/rdt+xWO7Fz5wkU7UZhvm3Ru8uiiqilZbsgZcZuHaSIcF/7PNp+TkD0mGve9ZWnFmunBCQSjCj45ZF1G9hr5D8aUhm/WgTDBUxGpm2zZbhBjoCXVze9bUevklXzfKbe/bFScYDyugoaKSg/PHJZju0zRzzohyjlnmWdp09FsdiaM3BXZuOqhg=
  - secure: CMlQ1z9yIjUX0Z5kMfuPmHyQECGXjm0S1ev/VNxCdV/y0gBkbna/gdhdQPMCYKhEzG6sFYeEErXF4wilSrAKQw38ia3kIeF+pmjCGWvjKNio3w8YEOHVNKKtxEcjtdGOWHL6oHgUia1KfEqRcFXqbMFitFN0F4eic7U557MuUbKw6bVIm/G/RudqHHmsmmGSx3SH4ZeFtcmxwtx8t85DZYX7/zR8xj+3cn4oHWq6xT1tDS7IewFpIHtZCyt1qp9veSgR0RK2YOX1ORMzaxWi2nCTidF+eP89vhJT98rqUF/TKz2uD4X1ItJEnMI0ePAnigc8HqRpY9f7DjKzbhaQYaN4LqMjAWl1+alGyIas3nQRkHjo4sU9JmWwJJ+9CU24/7dM3yD9HiKXa86Y8NCEJi5Utu5eMw2v7+b8d5Qt2h2ZVlBMdUt6tLDlwikIPhlbu7Jg5GhCrYjujiXW4aW25D5hBFatp6Cr6A4GZKNJdRFHmSksak3O6GSE8s/fcQ5t05bKZXl43F11OjDz+Yy/WQatpzqS4nqwuaphkxsqgMPSAn3XiCboumh+yiAJp1ERcbl6dSkNHTQ+WKD4Lz25X53XET6sv2fxOIEUJJuWHVj15cLDvCbdltNqpN3YqFsHqRkbzVhrTRl5Bnl2sXFLo50aPOs9xOzJw/94N54LVcc=
